@startuml

hide footbox
participant "Lamm Consulting"  as LM #FFFFFF
participant  "RISE" as RISE #FFFFFF
participant  "Vinnova" as VINN  #FFFFFF
participant  "MSB" as MSB  #FFFFFF
participant  "CERT-SE" as CERT #FFFFFF
participant  "Cybernode" as CYBER  #FFFFFF
participant  "NCC-SE" as NCC #FFFFFF
participant  "SVK" as SVK  #FFFFFF
participant  "Energimyndigheten" as EM #FFFFFF
participant  "PTS" as PTS #FFFFFF
participant  "Cybercampus" as KTH #FFFFFF
participant  "SKV" as SKV #FFFFFF
participant  "Försvarsdepart" as FORSVAR #FFFFFF
participant  "NCSC" as NCSC #FFFFFF
participant  "PRV" as PRV #FFFFFF
participant  "RRV" as RRV #FFFFFF
participant  "ISP" as ISP #FFFFFF
participant  "Civilministern" as CIV #FFFFFF
participant  "Internetstiftelsen" as IS #FFFFFF
participant  "Folk och Försvar" as FF #FFFFFF
participant  "Handelshögskolan" as HH #FFFFFF
participant  "KKVRA" as KKVRA #FFFFFF

LM -> LM:  Consulting 
note right #FFFFFF : Customer approved to publish project as open source\nbomresolver.io 
LM -> CYBER:  2022 02 28
note right #FFFFFF : Aktiverar och avgränsar en vilande arbetsgrupp\nSäkra leveranskedjor
CYBER -> KTH: 2022 03 08 
note right #FFFFFF : Håller föreläsning hos chains.proj.kth.se\n\nbomresolver.io FOSSDEM 2022\n\nÖnskemål om engelska i arbetsgruppen
LM -> LM:  2023 08 07
note right #FFFFFF : Förfrågan från kund utanför Sverige att delta i gruppen\nIngår sekretess avtal med kund\nKravställning gateway för energi
CYBER -> LM:  2023 08 28
note right #FFFFFF : Överlämning av arbetsgruppen till ny gruppledare
LM -> VINN: 2024 03 13 
note right #FFFFFF : Ansökan: säker bootloader\n\nAvslag: 2026 05 31 
LM -> MSB: 2024 04 30 
note right #FFFFFF : Fråga: Jag har funnit en svaghet \n\nSvar: Kontakta respektive tillsynsmyndighet\n
LM -> FORSVAR: 2024 05 27 
note right #FFFFFF : Skrev ett eget yttrande avseende NIS2 betänkandet\nTema Dual-Use, Energi samt Inre hot
LM -> SVK:  2024 06 10 
note right #FFFFFF : Cybersäkerhetskurs hos Svenska Kraftnät 
LM -> SVK: 2024 06 10 
note right #FFFFFF : Fråga: Jag har funnit en svaghet \n\nSvar: Oklart om vi kan hjälpa\n\nHänvisning: Energimyndigheten\n\nInformell förfrågan under kursen
LM -> EM: 2024 06 28 
note right #FFFFFF : Fråga: Jag har funnit en svaghet
LM -> MSB: 2024 09 12 
note right #FFFFFF : Ansökan: Beskriver problem i ansökan\n\nSöker 240.000 för att utveckla en lösning\n\nAvslag meddelas: 2024 12 10
LM -> PTS: 2024 09 19 
note right #FFFFFF : Fråga: Jag har funnit en svaghet\n\nHänvisning: Vi kan stödja, men ansvaret är Energimyndighetens
LM -> EM: 2024 10 16 
note right #FFFFFF : Fråga: Påminnelse\n\nHänvisning: CERT-SE
LM -> PRV: 2024 11 21 
note right #FFFFFF : Patentansökan lämnas in
LM -> CERT: 2024 11 28 
note right #FFFFFF : Fråga: Jag har funnit en svaghet\n\nÄrende CERT-SE #481380\n\nHänvisning: MSB ncc-se@msb.se
LM -> RISE: 2024 12 13 
note right #FFFFFF : Fråga: Jag har funnit en svaghet\n\nRISE har rapporterat samma problem för värmepumpar\n\nSvar: Vi återkommer
LM -> KTH: 2025 01 09 
note right #FFFFFF : Överlämnar dator och rapport\n\nKTH föreslår master thesis\n\nFinansiering behövs
LM -> SKV: 2025 02 16 
note right #FFFFFF : Önskemål: Betinga skattereduktion av att\nprodukter riktade mot konsument\nuppfyller hög cybersäkerhet
LM -> NCC: 2025 02 18 
note right #FFFFFF :Fråga: Jag har funnit en svaghet\nSvar: Kolla våra utlysningar 
LM -> NCSC: 2025 02 18 
note right #FFFFFF :Fråga: Jag har funnit en svaghet 
LM -> VINN: 2025 02 19 
note right #FFFFFF : Behov av reaktiva åtgärder 
LM -> CYBER:  2025 02 19
note right #FFFFFF : Jag fick berätta om problemet på cybernodens medlemsmöte
LM -> RRV:  2025 03 01 
note right #FFFFFF : Vi uppfattar det som en uppmaning att granska cybersäkerhet i energisystem
LM -> ISP:  2025 03 14 
note right #FFFFFF : Reglering av stark cryptering slår tillbaka på kritisk infrastruktur\nSvårt att förena med multipla användingsområden
LM -> CIV:  2025 03 20 
note right #FFFFFF : Noterade svagt intresse från media då civilministern presenterande cybersäkerhetsstrategi\nAvsaknad av reaktiv förmåga i handlingsplanen som presenterats.
LM -> SKV:  2025 03 25 
note right #FFFFFF : Lyfte problemet vid en konferens www.sekenergiforum.com.
LM -> IS:  2025 03 28 
note right #FFFFFF : Stiftelsen har fått medel av Vinnova för att kartlägga IoT
LM -> FF:  2025 05 12 
note right #FFFFFF : https://folkochforsvar.se/event/innovation-motorn-i-var-forsvarsformaga 1:23 Carl Heath 
LM -> HH:  2025 06 10 
note right #FFFFFF : https://www.hhs.se/sv/forskning/center/center-for-security-and-resilience/ Beskrev problem, inkluderade bilaga 
LM -> KKVRA:  2026 02 20 
note right #FFFFFF : https://kkrva.se/slutrapport-sv-a-r-vintersymposiet-videoinspelning-med-engelska-undertitlar-och-svensk-sammanfattning/ 2.38  
@enduml

